name: Build Movie App APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Nâng cấp lên v4

      - name: Set up Java
        uses: actions/setup-java@v4 # Nâng cấp lên v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.0"

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --no-tree-shake-icons

      - name: Upload APK
        uses: actions/upload-artifact@v4 # Đảm bảo đây là v4
        with:
          name: MovieApp-User-APK
          path: build/app/outputs/flutter-apk/app-release.apk
